### ISSUE TITLE
Identical functions

### ISSUE THREAD

**Issue by ldittmar81** [Gretelchen/Weather-App#2]
The functions showTemperature and displayWeather are identical. You can delete one of these.

https://github.com/Gretelchen/Weather-App/blob/f50055c4ae0d84615c70464dfe8a500c6a7ba007/index.js#L69

https://github.com/Gretelchen/Weather-App/blob/f50055c4ae0d84615c70464dfe8a500c6a7ba007/index.js#L87

In the last line: `axios.get(apiUrl).then(displayWeather); `  you can also write `axios.get(apiUrl).then(showTemperatur);` and delete the displayWeather function.

**Comment by Gretelchen** [comment]
fixed 🤩 
removed line 69 `function showTemperature(response) {`
and changed line 49 `  axios.get(apiUrl).then(displayWeather);`
